### PR TITLE
Map leader to space key

### PR DESCRIPTION
**Pull request by mkoppmann**
Fixes issue #58

### CODE REVIEW

**Comment by salcode** [comment]
@mkoppmann 

My apologies, I tried to rebase this PR before merging but I'm not sure if you get credit for Hacktoberfest if I do this.  You may have received some notifications from GitHub because of this.

When you have a chance would you please rebase your PR and then I'll merge it in so you get credit.

**Comment by mkoppmann** [comment]
Hi @salcode, thanks for thinking about the Hacktoberfest credit :)
Only PRs in October are counted so I you don’t mind, I will do it on Saturday, ok?

**Comment by salcode** [comment]
@mkoppmann Good point, Saturday is fine.  You might want to close this PR and open a new one at that time since I'm not sure if the date is based on when the PR is opened or when it is merged.

**Comment by mkoppmann** [comment]
Thank you, that’s kind of you. Found also some nice tricks in your project so it was already worth it :+1:

**Pull request closed without merging**
