### PR TITLE
Add set cursorline

### LINKED ISSUE #63: Add set cursorline
Highlight the current line

```
set cursorline
```

screenshot 2016-10-03 10 45 01

### PR DESCRIPTION
**Pull request by mkoppmann**
Fixes #63 

I added it at the end of the file, so the other line numbers don’t change.

### CODE REVIEW

**Comment by mkoppmann** [comment]
Hm, somehow the other commit got into this pull request. Well, I hope that’s no problem.

**Comment by salcode** [comment]
@mkoppmann 

No problem.  Thanks for the fixes.

I've gotten a lot of great feedback from other developers when creating PRs and it really helped me with my Git workflow.  I hope you don't mind that I'm sharing some of that information below.

Feel free to ignore it but I thought you might find it interesting.

The reason both commits ended up in the same PR is because you are using your `master` branch for both of them.

Generally, it is a good idea to create a new branch when creating a PR (the new branch should include your initials and the issue number)

e.g.

```
# Make the new branch
git branch mk/set-cursorline-63

# Switch to the new branch
git branch mk/set-cursorline-63

# ... Add your commits here

git push

# Then make your PR from mkoppmann/mk/set-cursorline-63 to salcode/master
```

It takes some getting used to but it makes it easy to then go back to `master` (which is unchanged) and create an unrelated PR.

```
git checkout master
git branch mk/tilde-toggle-quotes-56
git checkout mk/tilde-toggle-quotes-56
# ...
```

One other note is when writing your commit message, instead of using one line (I'm guessing you're using `git commit -m 'commit message'`), leave out the `-m` so it opens the editor and you make your commit message there.

Putting `Fixes #63` on its own line in your commit message will auto-close issue 63, when the commit is merged.

Here is a long read on [How to Write a Git Commit Message](http://chris.beams.io/posts/git-commit/).

Anyway, thanks again for the PRs.  I appreciate them.

**Comment by mkoppmann** [comment]
Wow, thanks for this great write-up.

You’re totally right, the correct way is to create a branch for every feature/issue. It’s also the recommended workflow for Github.
By the way `git checkout -b new-branch` automatically creates and switches to a new branch :)

Yes, I’m using `git commit -am "msg"`. I didn’t know, that issues get closed automatically with the commit message. I just put it in the pull request. Great to know, thanks :+1:

**Comment by salcode** [comment]
Glad it was helpful.

`git checkout -b new-branch` is nice 👍

**Pull request merged**
